name: Basic-Schulung 

on: 
 push: 
 workflow_dispatch: 
 
 jobs:
  build: 
    name: My-first-Actions
    runs-on: unbuntu-latest
    steps: 
    -uses: actions/chekut@v2
    -uses: ./action-a
     with: 
       MY_NAME: Flavia-Isabella 
